import type { Task, Project } from "@spectron/frontend/components/feature/task";

export const initialTasks: Task[] = [
  {
    id: "SP-123",
    title: "New GitLab integration",
    status: "In progress",
    updated: "4h ago",
    preview: "We need to clarify the webhook events",
    initials: "AM",
    color: "sand",
    time: "2m",
    unread: 2,
  },
  {
    id: "SP-122",
    title: "A home for all our conversations",
    status: "In progress",
    updated: "6h ago",
    preview: "This feels like the right direction",
    initials: "NK",
    color: "sage",
    time: "18m",
  },
  {
    id: "SP-121",
    title: "Connect GitHub repositories",
    status: "In review",
    updated: "Yesterday",
    preview: "PR is ready for a second pair of eyes",
    initials: "JL",
    color: "lavender",
    time: "42m",
    unread: 1,
  },
  {
    id: "SP-120",
    title: "Task creation from a message",
    status: "Todo",
    updated: "Yesterday",
    preview: "Added a few thoughts to the spec",
    initials: "AM",
    color: "sand",
    time: "1h",
  },
  {
    id: "SP-119",
    title: "Slack workspace sync",
    status: "In progress",
    updated: "Yesterday",
    preview: "Channel mapping works now",
    initials: "JL",
    color: "lavender",
    time: "2h",
  },
  {
    id: "SP-118",
    title: "Agent permissions",
    status: "Todo",
    updated: "Sep 4",
    preview: "Let's start with read-only access",
    initials: "NK",
    color: "sage",
    time: "3h",
  },
  {
    id: "SP-117",
    title: "Notifications that matter",
    status: "Todo",
    updated: "Sep 4",
    preview: "Only when something needs you",
    initials: "AM",
    color: "sand",
    time: "5h",
  },
  {
    id: "SP-116",
    title: "Set up the monorepo",
    status: "Done",
    updated: "Sep 3",
    preview: "All checks passed. We're good to go",
    initials: "NK",
    color: "sage",
    time: "1d",
  },
];

export const projects: Project[] = [
  { name: "Spectron", initial: "S", color: "project-spectron" },
  { name: "Orbit", initial: "O", color: "project-orbit" },
  { name: "Studio", initial: "S", color: "project-studio" },
];
