#!/usr/bin/env bash
#
# The remote half of provisioning. Not meant to be run by hand — invoke
# deployment/provision-app.sh from your workstation, which stages this file
# and the nginx templates on the box and then runs it as root.
#
# It is additive by design: the host is shared with testron, so nothing here
# touches a file outside /opt/spectron, /data/spectron, the two spectron nginx
# sites and the deploy user's authorized_keys — and it never rewrites the
# host's SSH configuration.
set -euo pipefail
umask 077
export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export DEBIAN_FRONTEND=noninteractive

die() { printf 'Error: %s\n' "$*" >&2; exit 1; }
note() { printf '   %s\n' "$*"; }
warn() { printf '   ! %s\n' "$*" >&2; }

[ "$(id -u)" -eq 0 ] || die 'Root privileges required'

STAGE=${1:?Internal staging directory required}
# Generated by provision-app.sh with printf %q from validated values.
# shellcheck source=/dev/null
. "$STAGE/settings.sh"

DOMAINS='app.spectron.dev spectron.dev'

# Per-project, so a testron run and a spectron run do not block each other.
exec 9>/run/lock/spectron-provision.lock
flock -n 9 || die 'Another spectron provision run is active'

# shellcheck source=/dev/null
. /etc/os-release
case "$ID:$VERSION_ID" in
  debian:12|debian:13) ;;
  *) die "Unsupported OS: $ID $VERSION_ID (this script knows Debian 12 and 13 with systemd)" ;;
esac

# ── packages ─────────────────────────────────────────────────────────────────

installed() {
  [ "$(dpkg-query -W -f='${Status}' "$1" 2>/dev/null || true)" = 'install ok installed' ]
}

install_packages() {
  local pkg missing=()
  for pkg in nginx certbot curl ca-certificates; do
    installed "$pkg" || missing+=("$pkg")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    apt-get update
    apt-get install -y "${missing[@]}"
  fi

  missing=()
  for pkg in docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin; do
    installed "$pkg" || missing+=("$pkg")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    # Docker CE from Docker's own signed repository, not the distribution's,
    # and not by piping their install script into a shell. Refuse rather than
    # let apt silently remove a working distribution Docker underneath a
    # running project.
    for pkg in docker.io docker-compose docker-compose-v2 docker-doc docker-buildx podman-docker containerd runc; do
      installed "$pkg" && die "Conflicting package $pkg is installed; migrate it to Docker CE before provisioning"
    done
    install -d -m 0755 /etc/apt/keyrings
    curl -fsSL "https://download.docker.com/linux/$ID/gpg" -o "$STAGE/docker.asc"
    install -m 0644 "$STAGE/docker.asc" /etc/apt/keyrings/docker.asc
    cat > /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/$ID
Suites: ${VERSION_CODENAME}
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF
    apt-get update
    apt-get install -y "${missing[@]}"
  fi

  # certbot.timer is what renews; nothing notices for sixty days if it is off.
  systemctl enable --now docker nginx certbot.timer >/dev/null

  # Container logs are the classic way a small VPS fills its disk, and the
  # default is unbounded. Only written if nothing already configured the
  # daemon — this host is shared, and that file is not ours to overwrite.
  if [ ! -e /etc/docker/daemon.json ]; then
    install -d -m 0755 /etc/docker
    cat > /etc/docker/daemon.json <<'JSON'
{
  "log-driver": "json-file",
  "log-opts": { "max-size": "50m", "max-file": "5" }
}
JSON
    systemctl restart docker
    note 'wrote /etc/docker/daemon.json (log rotation)'
  fi

  note "docker $(docker --version | cut -d' ' -f3 | tr -d ,), compose $(docker compose version --short), nginx $(nginx -v 2>&1 | sed 's|.*/||'), certbot $(certbot --version 2>&1 | cut -d' ' -f2)"
}

# ── the deploy user and the data directories ─────────────────────────────────

prepare_host() {
  local home key added=0

  if ! id "$DEPLOY_USER" >/dev/null 2>&1; then
    useradd --create-home --shell /bin/bash "$DEPLOY_USER"
    note "created $DEPLOY_USER"
  fi
  # Restricted by what it can reach, not by a shell: the deploy needs scp and
  # docker compose, and docker group membership is root-equivalent anyway.
  usermod -aG docker "$DEPLOY_USER"

  home=$(getent passwd "$DEPLOY_USER" | cut -d: -f6)
  [ -d "$home" ] || die "Missing home directory for $DEPLOY_USER"
  install -d -m 0700 -o "$DEPLOY_USER" -g "$(id -gn "$DEPLOY_USER")" "$home/.ssh"
  touch "$home/.ssh/authorized_keys"
  # Appended, never rewritten: testron's deploy key lives in this same file.
  while IFS= read -r key || [ -n "$key" ]; do
    case "$key" in ''|'#'*) continue ;; esac
    if ! grep -qxF -- "$key" "$home/.ssh/authorized_keys"; then
      # The leading newline also covers a file with no final newline.
      printf '\n%s\n' "$key" >> "$home/.ssh/authorized_keys"
      added=1
    fi
  done < "$STAGE/DEPLOY_KEY_FILE"
  chown "$DEPLOY_USER:$(id -gn "$DEPLOY_USER")" "$home/.ssh/authorized_keys"
  chmod 0600 "$home/.ssh/authorized_keys"
  [ "$added" = 1 ] && note 'authorized_keys: added the spectron deploy key' \
                   || note 'authorized_keys: the spectron deploy key is already present'

  # The workflow scp's compose.yaml and .env into this.
  install -d -m 0755 -o "$DEPLOY_USER" -g "$(id -gn "$DEPLOY_USER")" "$DEPLOY_PATH"

  # Never chowned recursively: this is the database, and after a restore it is
  # the only copy. Postgres manages the contents itself; the image's
  # entrypoint fixes ownership on first start.
  if [ -d "$DB_DATA" ] && [ -n "$(ls -A "$DB_DATA" 2>/dev/null)" ]; then
    note "$DB_DATA already holds a cluster; leaving it alone"
  else
    mkdir -p "$DB_DATA"
    chmod 0700 "$DB_DATA"
  fi

  # Written by the api container as node (uid 1000) and read by nginx inside
  # the app container. A bind mount keeps the host's ownership, so it is set
  # by number here — uid 1000 has a host account on this box, but it is not
  # the one the container means.
  mkdir -p "$FILES_DATA"
  chown 1000:1000 "$FILES_DATA"
  chmod 0755 "$FILES_DATA"

  note "$DEPLOY_PATH, $DB_DATA, $FILES_DATA ready"
}

check_ports() {
  local port owner
  # Nothing of ours is running yet, so anything answering on these ports is
  # someone else's — most likely testron, which lives on 4400 and 4401.
  for port in "$APP_PORT" "$WEB_PORT"; do
    owner=$(ss -ltnp "sport = :$port" 2>/dev/null | awk 'NR>1{print $NF; exit}')
    if [ -n "$owner" ]; then
      warn "port $port is already held by $owner; pick different APP_PORT/WEB_PORT values"
    fi
  done
}

check_ssh_policy() {
  # Not changed here: the host's SSH policy belongs to whoever provisioned the
  # box first, and two projects writing competing drop-ins is how a box locks
  # everyone out. Saying so is still worth a line.
  if sshd -T 2>/dev/null | grep -qx 'passwordauthentication yes'; then
    warn 'sshd still accepts passwords. Harden it separately; this script does not touch SSH.'
  fi
}

# ── nginx and certificates ───────────────────────────────────────────────────

nginx_backup=''
nginx_pending=0
rollback() {
  local rc=$? name
  trap - EXIT
  if [ "$nginx_pending" = 1 ]; then
    printf 'Restoring the spectron nginx sites from %s\n' "$nginx_backup" >&2
    for name in $DOMAINS; do
      rm -f "/etc/nginx/sites-available/$name.conf" "/etc/nginx/sites-enabled/$name.conf"
      if [ -f "$nginx_backup/$name.conf" ]; then
        cp -a "$nginx_backup/$name.conf" "/etc/nginx/sites-available/$name.conf"
        [ ! -f "$nginx_backup/$name.enabled" ] \
          || ln -sfn "/etc/nginx/sites-available/$name.conf" "/etc/nginx/sites-enabled/$name.conf"
      fi
    done
    if nginx -t && systemctl reload nginx; then
      rm -rf "$nginx_backup"
      nginx_pending=0
    else
      printf 'nginx rollback failed; the backup is retained at %s\n' "$nginx_backup" >&2
    fi
  fi
  exit "$rc"
}
trap rollback EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

has_cert() {
  [ -s "/etc/letsencrypt/live/$1/fullchain.pem" ] && [ -s "/etc/letsencrypt/live/$1/privkey.pem" ]
}

names_for() {
  case "$1" in
    spectron.dev) [ "$INCLUDE_WWW" = 1 ] && printf 'spectron.dev www.spectron.dev' || printf 'spectron.dev' ;;
    *) printf '%s' "$1" ;;
  esac
}

render_sites() {
  local domain names response target
  for domain in $DOMAINS; do
    names=$(names_for "$domain")
    target="/etc/nginx/sites-available/$domain.conf"
    # Before the certificate exists the TLS block cannot be installed at all —
    # nginx will not start with a missing certificate file. 503 on HTTP is the
    # honest placeholder; the ACME location stays live either way.
    response='return 503;'
    # shellcheck disable=SC2016 # $host and $request_uri are nginx's.
    has_cert "$domain" && response='return 301 https://$host$request_uri;'
    sed -e "s/__NAMES__/$names/g" -e "s|__HTTP_RESPONSE__|$response|g" \
      "$STAGE/nginx/http.conf" > "$target"
    if has_cert "$domain"; then
      sed -e "s/__WEB_NAMES__/$names/g" \
          -e "s/__APP_PORT__/$APP_PORT/g" \
          -e "s/__WEB_PORT__/$WEB_PORT/g" \
        "$STAGE/nginx/$domain.conf" >> "$target"
    fi
    chmod 0644 "$target"
    ln -sfn "$target" "/etc/nginx/sites-enabled/$domain.conf"
  done
  nginx -t
  systemctl reload nginx
}

configure_nginx() {
  local domain names name args
  command -v nginx >/dev/null || die 'Run a full provision to install nginx first'

  if [ "$MODE" = nginx ]; then
    for domain in $DOMAINS; do
      has_cert "$domain" || die "Missing the $domain certificate; run --certs-only or a full provision"
    done
  fi
  if [ "$MODE" != nginx ] && [ "$SKIP_CERTS" = 0 ]; then
    command -v certbot >/dev/null || die 'Run a full provision to install certbot first'
  fi
  # If www is meant to be on the apex certificate but is not, a render would
  # put the name on a server block whose certificate does not cover it.
  if { [ "$MODE" = nginx ] || [ "$SKIP_CERTS" = 1 ]; } && [ "$INCLUDE_WWW" = 1 ] && has_cert spectron.dev; then
    openssl x509 -in /etc/letsencrypt/live/spectron.dev/fullchain.pem -noout -checkhost www.spectron.dev \
      | grep -q 'does match certificate' || die 'Issue a certificate covering www with --certs-only first'
  fi

  # The whole nginx configuration has to be valid before this run starts, or
  # a failure here would roll back to something that was already broken.
  nginx -t

  # Scoped to the two files this project owns, so a rollback cannot revert a
  # change testron made to its own sites in the meantime.
  nginx_backup=$(mktemp -d /var/backups/spectron-nginx.XXXXXXXX)
  for domain in $DOMAINS; do
    [ ! -f "/etc/nginx/sites-available/$domain.conf" ] \
      || cp -a "/etc/nginx/sites-available/$domain.conf" "$nginx_backup/$domain.conf"
    [ ! -e "/etc/nginx/sites-enabled/$domain.conf" ] || : > "$nginx_backup/$domain.enabled"
  done
  nginx_pending=1

  install -d -m 0755 /var/www/certbot
  render_sites

  if [ "$MODE" != nginx ] && [ "$SKIP_CERTS" = 0 ]; then
    install -d -m 0755 /etc/letsencrypt/renewal-hooks/deploy
    # Ours rather than a shared one, so spectron's renewals do not depend on a
    # hook another project installed. Reloading nginx twice costs nothing.
    cat > /etc/letsencrypt/renewal-hooks/deploy/spectron-nginx <<'EOF'
#!/bin/sh
set -eu
nginx -t
systemctl reload nginx
EOF
    chmod 0755 /etc/letsencrypt/renewal-hooks/deploy/spectron-nginx

    for domain in $DOMAINS; do
      args=(--cert-name "$domain")
      for name in $(names_for "$domain"); do args+=(-d "$name"); done
      # --keep-until-expiring makes a re-run a no-op until renewal is due;
      # --expand picks up www being added to the apex later.
      if [ -n "$CERT_EMAIL" ]; then
        args+=(--email "$CERT_EMAIL")
      else
        # "unsafely" is wording from an era when the contact meant something;
        # Let's Encrypt discards it now. An existing account is reused, and
        # this flag only matters when there is none.
        args+=(--register-unsafely-without-email)
      fi
      certbot certonly --webroot -w /var/www/certbot "${args[@]}" \
        --agree-tos --non-interactive \
        --keep-until-expiring --expand \
        || die "certbot failed for $domain. /var/log/letsencrypt/letsencrypt.log has the reason."
      note "$domain certificate ok"
    done
    # Again, now that the certificates exist and the TLS blocks can be written.
    render_sites
    systemctl enable --now certbot.timer >/dev/null
  fi

  for domain in $DOMAINS; do
    has_cert "$domain" || warn "$domain has no certificate yet; it answers 503 on HTTP until one is issued"
  done

  nginx_pending=0
  rm -rf "$nginx_backup"
}

if [ "$MODE" = full ]; then
  install_packages
  prepare_host
  check_ports
  check_ssh_policy
fi
configure_nginx
